include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false
    prefer_single_quotes: true
    sort_pub_dependencies: false
    require_trailing_commas: false
    body_might_complete_normally_nullable: false

