name: cat_alogue
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_auth: ^3.3.10
  firebase_core: ^1.13.1
  firebase_storage: ^10.2.9
  cloud_firestore: ^3.1.10

  # UI
  lottie: ^1.4.2
  flutter_staggered_grid_view: ^0.6.2
  photo_view: ^0.14.0
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.1.0
  dotted_border: ^2.0.0+2
  bot_toast: ^4.0.3
  timeline_tile: ^2.0.0
  flutter_slidable: ^2.0.0
  video_thumbnail: ^0.5.2

  # State Management
  hooks_riverpod: ^1.0.4
  flutter_hooks: ^0.18.5+1

  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Util
  flutter_form_builder: ^7.6.0
  form_builder_validators: ^8.3.0
  uuid: ^3.0.6
  stilo: ^2.0.0
  intl: ^0.17.0
  path_provider: ^2.0.11
  # audioplayers: ^0.19.1
  geocoding: ^2.0.5
  freezed_annotation:
  json_annotation:
  infinite_scroll_pagination: ^3.2.0

  # Device Services
  camera: ^0.10.0+1
  image_picker: ^0.8.5+3
  location: ^4.4.0

  # Sign-in
  google_sign_in: ^5.4.1
  sign_in_with_apple: ^4.1.0
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Util
  flutter_gen_runner:
  build_runner: ^2.2.0
  freezed:
  json_serializable:
  lint: ^1.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/img/
    - assets/avatars/
    - assets/info/
