name: cat_alogue
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_auth: ^1.4.1
  firebase_core: ^1.3.0
  cloud_firestore: ^2.2.2

  # UI
  lottie: ^1.1.0
  flutter_staggered_grid_view: ^0.4.0
  photo_view: ^0.11.1
  google_fonts: ^2.1.0
  font_awesome_flutter: ^9.1.0
  dotted_border: ^2.0.0
  timeline_tile: ^2.0.0

  # State Management
  hooks_riverpod: ^0.14.0+4
  flutter_hooks: ^0.17.0

  # Database
  hive: ^2.0.4

  # Util
  flutter_form_builder: ^6.0.1
  uuid: ^3.0.4
  stilo: ^2.0.0
  # audioplayers: ^0.19.1
  geocoding: ^2.0.0

  # Device Services
  camera: ^0.8.1+4
  image_picker: ^0.8.2
  location: ^4.3.0

  # Sign-in
  google_sign_in: ^5.0.4
  sign_in_with_apple: ^3.0.0
  flutter_signin_button: ^2.0.0

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Util
  lint: ^1.5.3
  build_runner: ^2.0.5

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/img/
